// Package tool implements Simon's tool registration and JSON-schema
// generation, mirroring Python's simon/tools/tool.py @tool decorator.
//
// Python derives a tool's name, description, and JSON schema from a
// function's __name__, docstring, and inspect.signature. Go retains none of
// that at runtime (compiled binaries don't keep parameter names), so tools
// are declared explicitly instead: name and description are passed as
// arguments, and the schema is generated by reflecting over a parameter
// struct's `json`/`jsonschema` tags via New. This is an intentional
// ergonomics change (function signature -> parameter struct), not a
// workaround defect.
package tool

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/invopop/jsonschema"

	"simon-go/internal/agent/response"
	"simon-go/internal/model"
	"simon-go/pkg/simonerr"
)

// Tool is a single callable tool: its wire-level identity (Name,
// Description, Schema) plus the Go function that executes it.
type Tool struct {
	Name        string
	Description string
	Schema      map[string]any
	fn          func(ctx context.Context, raw json.RawMessage) (string, error)
}

// Call invokes the tool with raw JSON arguments (as supplied by a model's
// tool-call request), unmarshalling into the parameter struct declared at
// registration time.
func (t Tool) Call(ctx context.Context, raw json.RawMessage) (string, error) {
	return t.fn(ctx, raw)
}

// Spec converts the tool into the provider-agnostic description passed to
// model.Model.Complete.
func (t Tool) Spec() model.ToolSpec {
	return model.ToolSpec{Name: t.Name, Description: t.Description, Parameters: t.Schema}
}

// New declares a tool whose parameters are described by the struct type P.
// P's fields determine the generated JSON schema via `json`/`jsonschema`
// struct tags (using github.com/invopop/jsonschema), the same tags used to
// unmarshal a model's tool-call arguments before calling fn.
func New[P any](name, description string, fn func(ctx context.Context, params P) (string, error)) Tool {
	schema := schemaFor[P]()
	return Tool{
		Name:        name,
		Description: description,
		Schema:      schema,
		fn: func(ctx context.Context, raw json.RawMessage) (string, error) {
			var params P
			if len(raw) > 0 {
				if err := json.Unmarshal(raw, &params); err != nil {
					return "", simonerr.NewToolError(fmt.Sprintf("tool %q: invalid arguments", name), err)
				}
			}
			return fn(ctx, params)
		},
	}
}

// NewRaw builds a Tool from an already-known JSON schema and a raw
// JSON-in/text-out function, bypassing New's struct-reflection schema
// generation. Intended for tools whose schema is only known at runtime —
// notably MCP tools, whose input schema comes from the remote server, not a
// Go type — mirroring Python's direct `Tool(name=..., schema=..., fn=...)`
// construction in simon/tools/mcp_client.py.
func NewRaw(name, description string, schema map[string]any, fn func(ctx context.Context, raw json.RawMessage) (string, error)) Tool {
	if schema == nil {
		schema = map[string]any{"type": "object", "properties": map[string]any{}}
	}
	return Tool{Name: name, Description: description, Schema: schema, fn: fn}
}

// schemaFor reflects P into a flat (non-$ref) JSON schema object, matching
// the {"type": "object", "properties": {...}, "required": [...]} shape
// Python's _build_schema produces.
func schemaFor[P any]() map[string]any {
	reflector := &jsonschema.Reflector{
		DoNotReference:            true,
		ExpandedStruct:            true,
		AllowAdditionalProperties: false,
	}
	var zero P
	raw := reflector.Reflect(zero)

	encoded, err := json.Marshal(raw)
	if err != nil {
		// Reflection over a concrete Go struct type cannot fail to marshal;
		// a panic here means schemaFor was misused (e.g. P is a channel/func
		// type), which is a programming error, not a runtime condition.
		panic(fmt.Sprintf("tool: failed to marshal generated schema: %v", err))
	}
	var schema map[string]any
	if err := json.Unmarshal(encoded, &schema); err != nil {
		panic(fmt.Sprintf("tool: failed to decode generated schema: %v", err))
	}

	delete(schema, "$schema")
	delete(schema, "$id")
	if _, ok := schema["type"]; !ok {
		schema["type"] = "object"
	}
	if _, ok := schema["properties"]; !ok {
		schema["properties"] = map[string]any{}
	}
	return schema
}

// Registry looks up tools by name for the ReAct loop.
type Registry struct {
	tools map[string]Tool
	order []string
}

// NewRegistry builds a Registry from a set of tools.
func NewRegistry(tools ...Tool) *Registry {
	r := &Registry{tools: make(map[string]Tool, len(tools))}
	for _, t := range tools {
		r.Add(t)
	}
	return r
}

// Add registers a tool, overwriting any previous tool with the same name.
func (r *Registry) Add(t Tool) {
	if _, exists := r.tools[t.Name]; !exists {
		r.order = append(r.order, t.Name)
	}
	r.tools[t.Name] = t
}

// Get looks up a tool by name.
func (r *Registry) Get(name string) (Tool, bool) {
	t, ok := r.tools[name]
	return t, ok
}

// List returns all registered tools in registration order.
func (r *Registry) List() []Tool {
	out := make([]Tool, 0, len(r.order))
	for _, name := range r.order {
		out = append(out, r.tools[name])
	}
	return out
}

// Specs returns the model.ToolSpec form of every registered tool, ready to
// pass to model.Model.Complete.
func (r *Registry) Specs() []model.ToolSpec {
	specs := make([]model.ToolSpec, 0, len(r.order))
	for _, name := range r.order {
		specs = append(specs, r.tools[name].Spec())
	}
	return specs
}

// Names lists every registered tool name, for error messages.
func (r *Registry) Names() []string {
	out := make([]string, len(r.order))
	copy(out, r.order)
	return out
}

// RunToolCall executes a model-requested tool call against reg, returning
// (resultText, isError). Errors (unknown tool, malformed arguments,
// exceptions) are returned as text with isError=true so the caller can feed
// them back to the model as an error tool result instead of crashing the
// run — mirroring Python's run_tool_call, shared by Agent and ToolRunner so
// both behave identically.
func RunToolCall(reg *Registry, call response.ToolCall) (string, bool) {
	t, ok := reg.Get(call.Name)
	if !ok {
		return fmt.Sprintf("Error: tool '%s' not found. Available: %s", call.Name, joinNames(reg.Names())), true
	}
	argsJSON, err := json.Marshal(call.Arguments)
	if err != nil {
		return fmt.Sprintf("Error running tool '%s': %v", call.Name, err), true
	}
	result, err := t.Call(context.Background(), argsJSON)
	if err != nil {
		return fmt.Sprintf("Error running tool '%s': %v", call.Name, err), true
	}
	return result, false
}

func joinNames(names []string) string {
	out := ""
	for i, n := range names {
		if i > 0 {
			out += ", "
		}
		out += n
	}
	return out
}
